config/routes.rb
Rails.application.routes.draw do
  resources :houses
  # resources :sermons
  resources :appointments, only: [:index, :new, :create, :show]
  resources :prayers, only: [:index, :new, :create, :show]

  # resources :admins
  # resources :members
  resources :churches
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # post "/signup", to: "users#create"
  # post "/login", to: "sessions#create"
  # delete "/logout", to: "sessions#destroy"
  # get "/me", to: "users#show"
  resources :videos, only: [ :new, :create, :show] do
    get 'download', on: :member
  end
  # root 'videos#index'
  get '/videos', to: 'videos#index'
  get '/videos/:id', to: 'videos#show'
  post '/prayers/create', to: 'prayers#create'
  post '/appointments/create', to: 'appointments#create'
  post '/video/create', to: 'videos#create'

  post '/church/create', to: 'ministry#create'
  get '/church/all', to: 'ministry#index'
  get '/church/:id', to: 'ministry#show'

  post "/superadmin/login", to: "master_sessions#create"
  post "/superadmin/signup", to: "masters#create"
  post "/downloads/create", to: "video_downloads#create"

  
  post "/member/signup", to: "members#create"
  post "/member/login", to: "member_sessions#create"
  delete "/member/logout", to: "member_sessions#destroy"

  post "/admin/signup", to: "admins#create"
  post "/admin/login", to: "admin_sessions#create"
  delete "/admin/logout", to: "admin_sessions#destroy"
  delete "/admin/delete_account", to: "admins#destroy"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
    # require 'securerandom'
    has_secure_password
    
    belongs_to :ministry
    has_many :members, through: :church
    has_many :sermons
    has_many :prayers
    validates :password,presence: true
    validates :email,uniqueness: true,presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
end

app/models/church.rb
class Church < ApplicationRecord
    has_many :members
    has_one :admin
  end
  

app/models/house.rb
class House < ApplicationRecord
end

app/models/master.rb
class Master < ApplicationRecord
    has_secure_password
end

app/models/member.rb
class Member < ApplicationRecord
    # require 'securerandom'
    has_secure_password
    validates :password_digest,confirmation: true
    # validates :password_confirmation, presence: true
    has_many :prayers
    belongs_to :ministry
    has_one :admin
    validates :email,uniqueness: true,presence: true
end

app/models/ministry.rb
class Ministry < ApplicationRecord
    has_many :members, dependent: :destroy
    has_one :admin, dependent: :destroy
end

app/models/prayer.rb
class Prayer < ApplicationRecord
    # belongs_to :member
end

app/models/superadmin.rb
class Superadmin < ApplicationRecord
    has_secure_password

end

app/models/video.rb
class Video < ApplicationRecord
  # include ActiveStorageBase64::Support::Base64Image
  # has_base64_image :image
  mount_uploader :video, VideoUploader
  mount_uploader :image, ImageUploader
  
  end
  

app/models/videodownload.rb
class Videodownload < ApplicationRecord
    # include ActiveStorageBase64::Support::Base64Image
    # has_base64_image :image
    # mount_uploader :video, VideoUploader
    mount_uploader :image, ImageUploader
    
end
    

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: %i[ show edit update destroy ]
  skip_before_action :authorized, only: [:index, :create]

  # GET /houses or /houses.json
  def index
    @houses = House.all
  end

  # GET /houses/1 or /houses/1.json
  def show
  end

  # GET /houses/new
  def new
    @house = House.new
  end

  # GET /houses/1/edit
  def edit
  end

  # POST /houses or /houses.json
  def create
    @house = House.new(house_params)

    # respond_to do |format|
    # if @house.save
    #   # format.html { redirect_to house_url(@house), notice: "House was successfully created." }
    #   # format.json { render :show, status: :created, location: @house }
    #   render json:@houses,status: :created
    # else
    #   # format.html { render :new, status: :unprocessable_entity }
    #   # format.json { render json: @house.errors, status: :unprocessable_entity }
    #   render json: @house.errors, status: :unprocessable_entity
    # end
      if @house.save
        # format.html { redirect_to house_url(@house), notice: "House was successfully created." }
        # format.json { render :show, status: :created, location: @house }
        render json:@houses,status: :created
      else
        # format.html { render :new, status: :unprocessable_entity }
        # format.json { render json: @house.errors, status: :unprocessable_entity }
        render json: @house.errors, status: :unprocessable_entity
      end
    # end
  end

  # PATCH/PUT /houses/1 or /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to house_url(@house), notice: "House was successfully updated." }
        format.json { render :show, status: :ok, location: @house }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1 or /houses/1.json
  def destroy
    @house.destroy

    respond_to do |format|
      format.html { redirect_to houses_url, notice: "House was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = House.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def house_params
      params.permit(:housename, :houselocation)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/churches_helper.rb
module ChurchesHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/masters_helper.rb
module MastersHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/ministry_helper.rb
module MinistryHelper
end

app/helpers/prayers_helper.rb
module PrayersHelper
end

app/helpers/sermons_helper.rb
module SermonsHelper
end

app/views/houses/_form.html.erb
<%= form_with(model: house) do |form| %>
  <% if house.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
        <% house.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :housename, style: "display: block" %>
    <%= form.text_field :housename %>
  </div>

  <div>
    <%= form.label :houselocation, style: "display: block" %>
    <%= form.text_field :houselocation %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/houses/_house.html.erb
<div id="<%= dom_id house %>">
  <p>
    <strong>Housename:</strong>
    <%= house.housename %>
  </p>

  <p>
    <strong>Houselocation:</strong>
    <%= house.houselocation %>
  </p>

</div>

app/views/houses/edit.html.erb
<h1>Editing house</h1>

<%= render "form", house: @house %>

<br>

<div>
  <%= link_to "Show this house", @house %> |
  <%= link_to "Back to houses", houses_path %>
</div>

app/views/houses/index.html.erb
<p style="color: green"></p>

<h1>Houses</h1>
<div id="houses">
  <% @houses.each do |house| %>
    <%= render house %>
    <p>
      <%= link_to "Show this house", house %>
    </p>
  <% end %>
</div>

<%= link_to "New house", new_house_path %>
@houses

app/views/houses/new.html.erb
<h1>New house</h1>

<%= render "form", house: @house %>

<br>

<div>
  <%= link_to "Back to houses", houses_path %>
</div>

app/views/houses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @house %>

<div>
  <%= link_to "Edit this house", edit_house_path(@house) %> |
  <%= link_to "Back to houses", houses_path %>

  <%= button_to "Destroy this house", @house, method: :delete %>
</div>